### ISSUE TITLE
Working S3 adapter 

### ISSUE THREAD

**Issue by Rahulsharma0810** [mmornati/docker-ghostblog#52]
I am getting Module not found when 

Error: Cannot find module '/var/lib/ghost/versions/2.27.0/core/server/adapters/storage/s3'

`
Error: Cannot find module '/var/lib/ghost/versions/2.27.0/core/server/adapters/storage/s3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.getStorage (/var/lib/ghost/versions/2.27.0/core/server/adapters/storage/index.js:57:42)
    at setupSiteApp (/var/lib/ghost/versions/2.27.0/core/server/web/site/app.js:85:93)
    at setupParentApp (/var/lib/ghost/versions/2.27.0/core/server/web/parent-app.js:50:36)
    at Child.settings.init.then.then.then (/var/lib/ghost/versions/2.27.0/core/server/index.js:106:52)
    at Child.tryCatcher (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/2.27.0/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

My Dockerfile installing ghost-s3-service as
`RUN mkdir -p $GHOST_INSTALL/content/storage/s3 \
    && cd $GHOST_INSTALL/content/storage/s3 \
    && npm install --prefix . ghost-s3-service`

and config.override.json

`  "storage": {
  "active": "s3",
  "s3": {
    "accessKeyId": "",
    "secretAccessKey": "+LYfedCZkIDlGTWNJEGo+iyxg",
    "region": "",
    "bucket": ""
    }
  },`

**Comment by mmornati** [comment]
Need to check it. But I think the S3 is a mofule right? So you have to add it to the modules folder (mount point of your dockerfile)?
